=== Pull-Request-Community/pull-request-community-website/schemas/people-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "PullRequest personal user profile",
  "default": {},
  "examples": [
    {
      "name": "מיכל פורג",
      "github": "MichalPorag",
      "facebook": "https://www.facebook.com/miporagi",
      "twitter": "https://twitter.com/MichalPorag",
      "linkedin": "https://www.linkedin.com/in/michal-porag-9522b5142/",
      "website": "https://medium.com/@miporagi",
      "description": "אני מיכל פורג, מפתחת פולסטאק ב-Skillset, סטודנטית למדעי המחשב באוניברסיטה הפתוחה ומנהלת את קהילת PullRequest. אני תורמת קוד בעיקר לפרויקט \"הייתי_שם\", זה אתר שמנציח עדויות של נפגעי אלימות במערכות יחסים מכל סוג ומקשר בינם לבין גורמים שיכולים לעזור להם (עוד בשלבי בנייה). אני אוהבת לצייר, לקרוא וחתולים.",
      "roles": ["Admin"]
    }
  ],
  "required": ["name", "github", "description"],
  "properties": {
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "Full name",
      "description": "Your full name, in Hebrew",
      "examples": ["מיכל פורג"]
    },
    "github": {
      "$id": "#/properties/github",
      "type": "string",
      "title": "GitHub Username",
      "pattern": "^[A-Za-z\\d](?:[A-Za-z\\d]|-(?=[A-Za-z\\d])){0,38}$",
      "description": "Your GitHub username",
      "examples": ["MichalPorag"]
    },
    "facebook": {
      "$id": "#/properties/facebook",
      "type": "string",
      "title": "Your Facebook profile URL",
      "format": "uri",
      "examples": ["https://www.facebook.com/miporagi"]
    },
    "twitter": {
      "$id": "#/properties/twitter",
      "type": "string",
      "title": "Your Twitter profile URL",
      "format": "uri",
      "examples": ["https://twitter.com/MichalPorag"]
    },
    "linkedin": {
      "$id": "#/properties/linkedin",
      "type": "string",
      "title": "Your LinkedIn Page",
      "format": "uri",
      "examples": ["https://www.linkedin.com/in/michal-porag-9522b5142/"]
    },
    "website": {
      "$id": "#/properties/website",
      "type": "string",
      "title": "Personal blog / website",
      "description": "Your personal blog or website (it has to be about you)",
      "format": "uri",
      "examples": ["https://medium.com/@miporagi"]
    },
    "website": {
      "$id": "#/properties/stackoverflow",
      "type": "string",
      "title": "Stackoverflow profile link",
      "description": "Your personal blog or website (it has to be about you)",
      "format": "uri",
      "examples": ["https://stackoverflow.com/users/1348195/benjamin-gruenbaum"]
    },
    "description": {
      "$id": "#/properties/description",
      "type": "string",
      "title": "Personal introduction",
      "description": "Technologies that you love, hobbies, fun-facts, and anything that you are passionate about. Are you an architect? Do you speak Chinese? Studied amusement park and roller coaster engineering? This is the place to brag!",
      "examples": [
        "אני מיכל פורג, מפתחת פולסטאק ב-Skillset, סטודנטית למדעי המחשב באוניברסיטה הפתוחה ומנהלת את קהילת PullRequest. אני תורמת קוד בעיקר לפרויקט \"הייתי_שם\", זה אתר שמנציח עדויות של נפגעי אלימות במערכות יחסים מכל סוג ומקשר בינם לבין גורמים שיכולים לעזור להם (עוד בשלבי בנייה). אני אוהבת לצייר, לקרוא וחתולים."
      ]
    },
    "roles": {
      "$id": "#/properties/roles",
      "type": "array",
      "title": "Community roles",
      "description": "Only people who have role on pull request community",
      "examples": [["Admin"]]
    }
  },
  "additionalProperties": true
}

=== Pull-Request-Community/pull-request-community-website/people/YishayMendelsohn.json
{
  "name": "ישי מנדלסון",
  "github": "myishay",
  "facebook": "https://www.facebook.com/myishay",
  "linkedin": "https://www.linkedin.com/in/yishay-mendelsohn-174493133/",
  "description": "מפתח בחברה datree.io ומנחה את הפודקאסט קוד פתוח יחד עם דימה ברוסילובסקי",
  "website": "https://openkodpod.com/"
}

=== Pull-Request-Community/pull-request-community-website/people/AdirSL.json
{
  "name": "אדיר סלוצקי",
  "github": "Adir-SL",
  "facebook": "https://www.facebook.com/slutzkis",
  "linkedin": "https://www.linkedin.com/in/adir-slutzki-1686189",
  "twitter": "https://twitter.com/adircode",
  "description": "מעצב UI/UX ומאסטר ב-CSS מרצה במכללות ברחבי הארץ ומכין שקשוקה מעולה, אוהב לעשות אנימציות ופרויקטים אישיים."
}

=== Pull-Request-Community/pull-request-community-website/people/AmitBarletz.json
{
  "name": "עמית ברלץ",
  "github": "abrl91",
  "linkedin": "https://www.linkedin.com/in/amitbarletz/",
  "website": "https://syntactic-sugar.netlify.app/",
  "twitter": "https://twitter.com/BarletzA52",
  "description": "מפתחת FrontEnd בחברה שנקראת PROFTIT. אוהבת לקרוא ספרים על פסיכולוגיה חיובית, לומדת לנגן על פסנתר, מכורה לריצה ולספורט באופן כללי. מנהלת יחד עם עוז, אורי ומיכל את Pull Request",
  "roles": ["Former admin"]
}

=== Pull-Request-Community/pull-request-community-website/YanivWeinshtein.json
{
    "name": "יניב ויינשטיין",
    "github": "YanivWein24",
    "linkedin": "https://www.linkedin.com/in/yaniv-weinshtein/",
    "website": "https://yaniv-portfolio.netlify.app/",
    "description": "הנדסאי אלקטרוניקה ומפתח פולסטאק אוטודידקט, מתמחה ב MERN Stack. בזמן המועט שבו אני לא על המחשב כנראה שתמצאו אותי בסוני. "
}

=== Pull-Request-Community/pull-request-community-website/people/ShirZabolotny.json
{
    "name": "שיר זבולוטני",
    "github": "shir0206",
    "facebook": "https://www.facebook.com/shir.klein.5",
    "linkedin": "https://www.linkedin.com/in/shir-zabolotny-a83b18109/",
    "website": "https://shir0206.github.io/ShirWeb/",
    "description": "אני שיר, מפתחת Front End שאוהבת גם ציורים גם טיולים וגם טיפול בצמחים!"
  }

=== Pull-Request-Community/pull-request-community-website/people/DaniSofer.json
{
  "name": "דני סופר",
  "github": "soferdani",
  "facebook": "https://www.facebook.com/soferdani",
  "twitter": "https://twitter.com/SoferDani",
  "linkedin": "https://www.linkedin.com/in/dani-sofer/",
  "description": "חיה עסקית עם אהבה לטכנולוגיה וקוד, מפתח פוולסטאק שמחפש אתרגים בהם אוכל להשפיע כמה שיותר. אני גם מנגן ביוקולהלה, גולש גלים, אוהב קפה ושחמט  "
}

=== Pull-Request-Community/pull-request-community-website/data/people/moshevilner.json
{
    "name": "משה וילנר",
    "github": "shootermv",
    "facebook": "https://www.facebook.com/moshe.vilner/",
    "twitter": "https://twitter.com/shootermv",
    "linkedin": "https://www.linkedin.com/in/moshe-vilner-7a7745a/",
    "website": "https://gs500coder.blogspot.com",
    "description": "אבא ,לשעבר תלמיד ישיבה, לשעבר פיאונר ממוסקוה. אדם מוזר וקצת מטורף שמנסה נואשות להפוך את עצמו למתכנת מצליח ואגדי. לך תדע, אולי יום אחד זה יצליח למרבה האירוניה"
}

=== Pull-Request-Community/pull-request-community-website/people/LiranTal.json
{
  "name": "לירן טל",
  "github": "lirantal",
  "facebook": "https://www.facebook.com/tliran",
  "twitter": "https://twitter.com/liran_tal",
  "linkedin": "https://www.linkedin.com/in/talliran/",
  "website": "https://lirantal.medium.com/",
  "description": "אני אוהב לקחת חלק בקהילות, פרויקטי קוד פתוח, ובאופן פרטני יותר בקהילות של נוד וג׳אווהסקריפט. רוב הזמן אני מתעסק במחקר של אבטחת תוכנה, ופעילויות העלאת המודעות לאבטחת קוד פתוח. אוהב כדורגל, לנגן, משחקי סימולציות טיסה, ולבנות כלים לשורת פקודה.",
  "roles": [""]
}
