=== Pull-Request-Community/pull-request-community-website/schemas/people-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "PullRequest personal user profile",
  "default": {},
  "examples": [
    {
      "name": "מיכל פורג",
      "github": "MichalPorag",
      "facebook": "https://www.facebook.com/miporagi",
      "twitter": "https://twitter.com/MichalPorag",
      "linkedin": "https://www.linkedin.com/in/michal-porag-9522b5142/",
      "website": "https://medium.com/@miporagi",
      "description": "אני מיכל פורג, מפתחת פולסטאק ב-Skillset, סטודנטית למדעי המחשב באוניברסיטה הפתוחה ומנהלת את קהילת PullRequest. אני תורמת קוד בעיקר לפרויקט \"הייתי_שם\", זה אתר שמנציח עדויות של נפגעי אלימות במערכות יחסים מכל סוג ומקשר בינם לבין גורמים שיכולים לעזור להם (עוד בשלבי בנייה). אני אוהבת לצייר, לקרוא וחתולים.",
      "roles": ["Admin"]
    }
  ],
  "required": ["name", "github", "description"],
  "properties": {
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "Full name",
      "description": "Your full name, in Hebrew",
      "examples": ["מיכל פורג"]
    },
    "github": {
      "$id": "#/properties/github",
      "type": "string",
      "title": "GitHub Username",
      "pattern": "^[A-Za-z\\d](?:[A-Za-z\\d]|-(?=[A-Za-z\\d])){0,38}$",
      "description": "Your GitHub username",
      "examples": ["MichalPorag"]
    },
    "facebook": {
      "$id": "#/properties/facebook",
      "type": "string",
      "title": "Your Facebook profile URL",
      "format": "uri",
      "examples": ["https://www.facebook.com/miporagi"]
    },
    "twitter": {
      "$id": "#/properties/twitter",
      "type": "string",
      "title": "Your Twitter profile URL",
      "format": "uri",
      "examples": ["https://twitter.com/MichalPorag"]
    },
    "linkedin": {
      "$id": "#/properties/linkedin",
      "type": "string",
      "title": "Your LinkedIn Page",
      "format": "uri",
      "examples": ["https://www.linkedin.com/in/michal-porag-9522b5142/"]
    },
    "website": {
      "$id": "#/properties/website",
      "type": "string",
      "title": "Personal blog / website",
      "description": "Your personal blog or website (it has to be about you)",
      "format": "uri",
      "examples": ["https://medium.com/@miporagi"]
    },
    "website": {
      "$id": "#/properties/stackoverflow",
      "type": "string",
      "title": "Stackoverflow profile link",
      "description": "Your personal blog or website (it has to be about you)",
      "format": "uri",
      "examples": ["https://stackoverflow.com/users/1348195/benjamin-gruenbaum"]
    },
    "description": {
      "$id": "#/properties/description",
      "type": "string",
      "title": "Personal introduction",
      "description": "Technologies that you love, hobbies, fun-facts, and anything that you are passionate about. Are you an architect? Do you speak Chinese? Studied amusement park and roller coaster engineering? This is the place to brag!",
      "examples": [
        "אני מיכל פורג, מפתחת פולסטאק ב-Skillset, סטודנטית למדעי המחשב באוניברסיטה הפתוחה ומנהלת את קהילת PullRequest. אני תורמת קוד בעיקר לפרויקט \"הייתי_שם\", זה אתר שמנציח עדויות של נפגעי אלימות במערכות יחסים מכל סוג ומקשר בינם לבין גורמים שיכולים לעזור להם (עוד בשלבי בנייה). אני אוהבת לצייר, לקרוא וחתולים."
      ]
    },
    "roles": {
      "$id": "#/properties/roles",
      "type": "array",
      "title": "Community roles",
      "description": "Only people who have role on pull request community",
      "examples": [["Admin"]]
    }
  },
  "additionalProperties": true
}

=== Pull-Request-Community/pull-request-community-website/data/people/urish.json
{
  "name": "אורי שקד",
  "github": "urish",
  "twitter": "https://twitter.com/UriShaked",
  "website": "https://urish.org/",
  "description": "אוהב לבנות פרוייקטים שמשלבים חומרה ותוכנה, למשל גרסה אמיתית של המשחק עם הדינוזאור מכרום. עובד על Wokwi, פלטפורמה לסימולציה של ארדואינו שרצה בדפדפן, וחלק מהצוות של Pull Request. מעצב דברים שימושיים לבית ומדפיס בתלת מימד. רקדן ומדריך סלסה ובעבר ניהלתי עם חברים את מועדון Salsa4Fun, שם גם הכרתי את אשתי. מנגן על חליל פאן. 🎶",
  "roles": ["Admin","Mentor"]
}

=== Pull-Request-Community/pull-request-community-website/people/HagarShilo.json
{
    "name": "הגר שילה",
    "github": "strayblues",
    "linkedin": "https://www.linkedin.com/in/hagar-shilo-04651511b",
    "website": "https://blog.hagarsh.com",
    "description": "בוגרת Google Summer of Code (התמחות קיץ בקוד פתוח) וכיום מפתחת פרונטאנד עצמאית. אוהבת לבנות פרויקטים אישיים, לומדת בלשנות קוגניטיבית, חובבת תפירה וכותבת בלוג טכנולוגי בנושא הסבה לפיתוח."
}

=== Pull-Request-Community/pull-request-community-website/people/GuyYaffe.json
{
  "name": "גיא יפה",
  "github": "guyyaffear",
  "linkedin": "https://www.linkedin.com/in/guy-yaffe-ermoza/",
  "description": "עשיתי הסבה מקריירה בטחונית בוטקאמפ 8 חודשים בColumbia University עובד כמפתח פרונט כימעט שלוש שנים ועושה תואר במדעי המחשב  תוך כדי אוהב מאוד מרוואל I AM GROOT אוסף פואפים כמובן רק של מרוואל אוהב לגלוש סנובורד וספורט לאכול פיצה  וכמובן LOL ולהנות "
}

=== Pull-Request-Community/pull-request-community-website/people/YuvalAboulafia.json
{
    "name": "יובל אבולעפיה",
    "github": "yuvalabou",
    "facebook": "https://www.facebook.com/yuval.abou/",
    "linkedin": "https://www.linkedin.com/in/yuvalaboudesign/",
    "description": "מעצב תעשייתי בהכשרתי ומייקר בנשמתי, אוהב ללמוד ולהתקדם בכל תחום שאני מוצא כמאתגר. כך הגעתי ללמוד קוד וגיטהב הפך לדף הבית שלי."
}

=== Pull-Request-Community/pull-request-community-website/people/BarakBrudo.json
{
  "name": "ברק ברודו",
  "github": "MrBLightning",
  "facebook": "https://www.facebook.com/barak.brudo/",
  "twitter": "https://twitter.com/BarakBrudo",
  "linkedin": "https://www.linkedin.com/in/barakbrudo/",
  "description": "בעבר מפתח Fullstack וכיום DevRel. התואר שלי בכלל בהוראת אמנות עם התמחות בצילום. עבדתי כמעצב גרפי ✨, עוזר צלם ⚡ ומדריך אמנויות לחימה 💪. אוהב לשיר ולהריץ משחקי מבוכים ודרקונים."
}

=== Pull-Request-Community/pull-request-community-website/people/shebeolga.json
{
  "name": "אולגה שבקו",
  "github": "shebeolga",
  "facebook": "https://www.facebook.com/olga.shebeko.5/",
  "linkedin": "https://www.linkedin.com/in/shebeolga/",
  "website": "https://shebeolga.medium.com/",
  "description": "אני מתכנתת חשדה. אהובת לפתור בעיור ולעשות דברים טובים ונחמדים. מקווה, שאוכל לעשות משהו משמעותי ושימושי"
}

=== Pull-Request-Community/pull-request-community-website/data/people/yanaiedri.json
{
    "name": "ינאי אדרי",
    "github": "yanai101",
    "facebook": "https://www.facebook.com/yanai.edri",
    "twitter": "https://twitter.com/yanaiEdri",
    "linkedin": "https://www.linkedin.com/in/yanaiedri/",
    "description": "מפתח למעלה מעשות וחצי כיום בסייבראק , ממייסדי קהילת המפתחים הגדולה של הדרום (Negev Web Developers) כותב מאמרים כשנתקל בנושאים מעניינים , מאמין גדול בתרומה לקהילת המפתחים ,מתחזק ערוץ טלגרם המעדכן מניוזלטרים שונים, נשוי +5 , בהכשרתי פראמדיק"
  }

=== Pull-Request-Community/pull-request-community-website/people/HilaFish.json
{
  "name": "הילה פיש",
  "github": "hilafish",
  "facebook": "https://www.facebook.com/hila.fish",
  "twitter": "https://twitter.com/Hilafish1",
  "linkedin": "https://www.linkedin.com/in/hila-fish",
  "website": "https://medium.com/@hilafish",
  "description": "אני עובדת כ- Senior DevOps Engineer, התרומה שלי לפרויקטי קוד פתוח כרגע היא בעיקר בהטמעתם בסביבות השונות בעבודה, כתיבת בלוג פוסטים על יוז קייסים של הטמעת כלי קוד פתוח וכן הפצת הבשורה בכנסים (כמרצה וכאורחת). מעבר לזה, אני סולנית בהרכב קאברים, מנהלת תוכנית בקהילת ״באות״ וחלק ממארגני כנסי DevOpsDays TLV ו-StatsCraft.",
  "roles": ["admin"]
}
