=== Pull-Request-Community/pull-request-community-website/schemas/people-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "PullRequest personal user profile",
  "default": {},
  "examples": [
    {
      "name": "מיכל פורג",
      "github": "MichalPorag",
      "facebook": "https://www.facebook.com/miporagi",
      "twitter": "https://twitter.com/MichalPorag",
      "linkedin": "https://www.linkedin.com/in/michal-porag-9522b5142/",
      "website": "https://medium.com/@miporagi",
      "description": "אני מיכל פורג, מפתחת פולסטאק ב-Skillset, סטודנטית למדעי המחשב באוניברסיטה הפתוחה ומנהלת את קהילת PullRequest. אני תורמת קוד בעיקר לפרויקט \"הייתי_שם\", זה אתר שמנציח עדויות של נפגעי אלימות במערכות יחסים מכל סוג ומקשר בינם לבין גורמים שיכולים לעזור להם (עוד בשלבי בנייה). אני אוהבת לצייר, לקרוא וחתולים.",
      "roles": ["Admin"]
    }
  ],
  "required": ["name", "github", "description"],
  "properties": {
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "Full name",
      "description": "Your full name, in Hebrew",
      "examples": ["מיכל פורג"]
    },
    "github": {
      "$id": "#/properties/github",
      "type": "string",
      "title": "GitHub Username",
      "pattern": "^[A-Za-z\\d](?:[A-Za-z\\d]|-(?=[A-Za-z\\d])){0,38}$",
      "description": "Your GitHub username",
      "examples": ["MichalPorag"]
    },
    "facebook": {
      "$id": "#/properties/facebook",
      "type": "string",
      "title": "Your Facebook profile URL",
      "format": "uri",
      "examples": ["https://www.facebook.com/miporagi"]
    },
    "twitter": {
      "$id": "#/properties/twitter",
      "type": "string",
      "title": "Your Twitter profile URL",
      "format": "uri",
      "examples": ["https://twitter.com/MichalPorag"]
    },
    "linkedin": {
      "$id": "#/properties/linkedin",
      "type": "string",
      "title": "Your LinkedIn Page",
      "format": "uri",
      "examples": ["https://www.linkedin.com/in/michal-porag-9522b5142/"]
    },
    "website": {
      "$id": "#/properties/website",
      "type": "string",
      "title": "Personal blog / website",
      "description": "Your personal blog or website (it has to be about you)",
      "format": "uri",
      "examples": ["https://medium.com/@miporagi"]
    },
    "website": {
      "$id": "#/properties/stackoverflow",
      "type": "string",
      "title": "Stackoverflow profile link",
      "description": "Your personal blog or website (it has to be about you)",
      "format": "uri",
      "examples": ["https://stackoverflow.com/users/1348195/benjamin-gruenbaum"]
    },
    "description": {
      "$id": "#/properties/description",
      "type": "string",
      "title": "Personal introduction",
      "description": "Technologies that you love, hobbies, fun-facts, and anything that you are passionate about. Are you an architect? Do you speak Chinese? Studied amusement park and roller coaster engineering? This is the place to brag!",
      "examples": [
        "אני מיכל פורג, מפתחת פולסטאק ב-Skillset, סטודנטית למדעי המחשב באוניברסיטה הפתוחה ומנהלת את קהילת PullRequest. אני תורמת קוד בעיקר לפרויקט \"הייתי_שם\", זה אתר שמנציח עדויות של נפגעי אלימות במערכות יחסים מכל סוג ומקשר בינם לבין גורמים שיכולים לעזור להם (עוד בשלבי בנייה). אני אוהבת לצייר, לקרוא וחתולים."
      ]
    },
    "roles": {
      "$id": "#/properties/roles",
      "type": "array",
      "title": "Community roles",
      "description": "Only people who have role on pull request community",
      "examples": [["Admin"]]
    }
  },
  "additionalProperties": true
}

=== Pull-Request-Community/pull-request-community-website/data/people/eldadfux.json
{
  "name": "אלדד פוקס",
  "github": "eldadfux",
  "facebook": "https://www.facebook.com/eldad.fux/",
  "twitter": "https://twitter.com/eldadfux",
  "linkedin": "https://www.linkedin.com/in/eldadfux/",
  "website": "https://appwrite.io",
  "description": "יזם, ארכיטקט תוכנה, אובססיבי על כל מה שקשור לקוד פתוח והיוצר של appwrite.io",
  "roles": ["Mentor"]
}

=== Pull-Request-Community/pull-request-community-website/people/SiorMeir.json
{
  "name": "סיאור מאיר",
  "github": "https://github.com/siorm2310",
  "facebook": "https://www.facebook.com/sior.meir",
  "linkedin": "https://www.linkedin.com/in/sior-meir",
  "description": "מהנדסה אווירונאוטיקה ומפתח תוכנה, חובב שפות (גם של בני אדם וגם של מחשבים) אך מתמקד כיום בפייתון, גיימר וחובב מחשבים מגיל צעיר",
  "roles": ["Developer"]
}

=== Pull-Request-Community/pull-request-community-website/data/people/AnnaDinaburgVulikh.json
{
    "name": "אנה דינבורג ווליך",
    "github": "AnnaDinaburgVulikh",
    "facebook": "https://www.facebook.com/dinaburg/",
    "twitter": "https://twitter.com/AnnaDinVu",
    "linkedin": "https://www.linkedin.com/in/anna-dinaburg-vulikh/",
    "description": "מהנדסת תעשייה וניהול, בתהליך הסבה לתחום התכנות. מתנדבת בשיקודס, סיימתי מסלול פייתון בארגון. אוהבת את כל סרטי מרוול וגם הסדרות ."
  }

=== Pull-Request-Community/pull-request-community-website/people/TomerBrisker.json
{
    "name": "תומר בריסקר",
    "github": "tbrisker",
    "facebook": "https://www.facebook.com/tomer.brisker/",
    "twitter": "https://twitter.com/tbrisker_pro",
    "linkedin": "https://www.linkedin.com/in/tbrisker/",
    "description": "כותב קוד פתוח מאז 1999, לפעמים גם מקבל על זה כסף. אוהב גם לאכול אוכל טוב, לשתות בירה, להרצות בכנסים ולטוס בעולם שאין בו מגפות, ובמיוחד לשלב הכל יחד."
}

=== Pull-Request-Community/pull-request-community-website/people/AdirKandel.json
{
  "name": "אדיר קנדל",
  "github": "adirkandel",
  "facebook": "https://www.facebook.com/adirkandel/",
  "linkedin": "https://www.linkedin.com/in/adir-kandel/",
  "description": "Full stack ביכולות אבל Front end developer בלב ❤️. אני לא גזען פשוט מאוהב ב- Vue. מנהל את הערוץ והבלוג של FED Cast IL.",
  "website": "https://fedcast.co.il"
}

=== Pull-Request-Community/pull-request-community-website/people/AnnaHino.json
{
  "name": "אנה הינו",
  "github": "angardia",
  "facebook": "https://www.facebook.com/anna.hino",
  "twitter": "https://twitter.com/Angardia",
  "linkedin": "https://www.linkedin.com/in/anna-hino-0838a7198/",
  "website": "https://codepen.io/angardia",
  "description": "מעריצת חתולים מושבעת, גיימרית, מחפשת משרת FRONT END ראשונה, מציירת בCSS ואוהבת בירות!!!"
}

=== Pull-Request-Community/pull-request-community-website/people/AvnerRussler.json
{
  "name": "אבנר רוסלר",
  "github": "avnerussler",
  "facebook": "https://www.facebook.com/AvneRussler/",
  "twitter": "https://twitter.com/AvneRussler",
  "linkedin": "https://www.linkedin.com/in/avnerussler/",
  "website": "https://portfolio-rose-iota.vercel.app/",
  "description": "משרת בצה״ל, חרדי לשעבר, כאן בשביל ללמוד להתפתח ולתרום"
}

=== Pull-Request-Community/pull-request-community-website/people/ErezHod.json
{
    "name": "ארז הוד",
    "github": "erezhod",
    "facebook": "https://www.facebook.com/erezhod",
    "twitter": "https://twitter.com/ErezHod",
    "linkedin": "https://www.linkedin.com/in/erezhod",
    "website": "https://erezhod.com",
    "description": "מייסד ומנכ\"ל חברת Hero Apps, Ltd. מפתח Full-Stack ב-Angular, Node, SQL וגם נייטיב מובייל ל-iOS/iPadOS. בזמני הפנוי אני אוהב לגיימר (יותר מדי World of Warcraft), לנהוג ברכבי ספורט, לשמוע Metal בווליום גבוהה במיוחד ולצפות בכמה שיותר סדרות אנימה."
}
